### ISSUE TITLE
Update to Gradle 7

### ISSUE THREAD

**Issue by SirYwell** [eldoriarpg/SemVerTools#1]
It doesn't work well with the error prone plugin for some reason.

**Comment by RainbowDashLabs** [comment]
@SirYwell I think we should close this since it is essentially fixed.
We could also consider to set the dev branch as default, which will cause PRs to target the dev branch by default and issues to be closed when merged into the dev branch.

**Comment by SirYwell** [comment]
> We could also consider to set the dev branch as default, which will cause PRs to target the dev branch by default and issues to be closed when merged into the dev branch.

That would also mean that people will see the develop branch first when visiting the repository. This feels a bit weird but I'll think about it.
