### ISSUE TITLE
feature: Use Java modules to hide internal code

### ISSUE THREAD

**Issue by SirYwell** [eldoriarpg/SemVerTools#9]
As we're on Java 11, we can use [java modules](https://www.oracle.com/corporate/features/understanding-java-9-modules.html) to encapsulate the internal code parts from the public API. 

This might require moving around existing classes and should therefore be done before version 1.0.0.

**Comment by iljakorneckis** [comment]
Hey hey! May I give this a shot?

**Comment by SirYwell** [comment]
Sure! It's important to target the develop branch for that.
